# Generated by Django 4.0.4 on 2022-04-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_product_group_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('notebook', 'notebook'), ('pc', 'pc'), ('mobile', 'mobile'), ('accessories', 'accessories')], default='mobile', max_length=20),
        ),
    ]
